name: Update Readme

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Profile details to make commit on your behalf
      - name: set user details
        run: |
            git config user.name PawanRoy1997
            git config user.email pawanroy0066@gmail.com

      # Runs a single command using the runners shell
      - name: Run the update script
        run: ./updateReadme.sh
